### ISSUE TITLE
Tracking of 1.0 release

### ISSUE THREAD

**Issue by Airblader** [Airblader/xcb-util-xrm#8]
This documents the necessary tasks for a first official release:

- [x] Allow arbitrary length `RESOURCE_MANAGER` strings and parse them correctly.
- [x] Handle escaped characters ( #10 ).
- [x] Move the resource struct back into the non-public part and instead introduce utility / converter functions. ( #3 )
- [x] Introduce validation that name and class query strings have the same length. ( #7 )
- [x] Handle case sensitivity properly. ( #4 )
- [x] Rename API to load database to something like `xcb_xrm_database_from_resource_manager`
- [x] Additional API for loading database from arbitrary strings.
- [x] Move resource type into the resource structure.
- [x] Fix matching ( #14 ).
- [ ] Fix greediness ( #15 ).
- [x] Document the entire API.
- [x] Change tests to (also?) compare against Xlib.
- [x] Ignore comments (necessary when loading from string). Also ignore `#` lines.
- [ ] Combine / Merge APIs ( #19 )
- [ ] CLI API ( #20 )
- [ ] Duplicates ( #22 )
- [ ] Put resources ( #23 )

**Comment by psychon** [comment]
Do you want to handle embedded `\0`-bytes correctly? I saw some example somewhere that used escape sequences (`\0\\\r\n` and whatever else) and I think your API can't handle this. Should it, or should people just not do something so stupid? :-)

**Comment by Airblader** [comment]
Why... Would someone do that. I guess it'd be nice to handle it, though I don't see it as a pressing issue for a first release unless it completely breaks the library. Especially for use cases like cairo where you only query something simple like the dpi. 

The fact of the matter is that the specs have a lot of complexity no one seems to be using in real life, at the same time both users and applications do things which violate the spec, but are accepted by Xlib. :/

One interesting question (we currently ignore) is whether the * wildcard should he greedy. But honestly, who would use that?

**Comment by Airblader** [comment]
(Sorry, that went a little off topic. To answer your question, I'd say we need it for the release if it breaks the library, otherwise it's something we can fix later on, imho. Opposing concerns or thoughts are of course welcome)

**Comment by psychon** [comment]
Fine with me, I just wanted to mention it. I wouldn't mind not handling `\0` at all.

**Comment by psychon** [comment]
And on "should * be greedy": No idea, but I guess "do what Xlib does" is the best option for this?

**Comment by Airblader** [comment]
> Fine with me, I just wanted to mention it. I wouldn't mind not handling \0 at all.

OK. Let's worry about this when the day comes, then. :)

> And on "should * be greedy": No idea, but I guess "do what Xlib does" is the best option for this?

Yeah. I've also written a small example application [xrmq](https://github.com/Airblader/xrmq). Next to having a reference, I want to extend it to also use Xlib and compare both results eventually. That should make it easier to figure out differences. Reading the Xlib code isn't really helpful, not to me anyway… :)

**Comment by Airblader** [comment]
@psychon Actually there's [an entire part](https://tronche.com/gui/x/xlib/resource-manager/file-syntax.html) of the spec dedicated to this, so we should probably support it.

That chapter also showed me that I didn't get how the format works entirely correct. I might have to change the parser and algorithm. :/ At least from the spec, `A?b` shouldn't be legal since `?` is different from `.` and `*` (it should be `A.?.b`). I'll have to see if Xlib accepts both, though.

**Comment by psychon** [comment]
Yup, that's the page were I got the "weird \000 example" from. :-)
Since this should likely be as compatible with Xlib as possible, perhaps it's a good idea to have the unit tests check the Xlib and this library produce the same results? If you want, I can try looking into implementing this, but it might take a while until I have the time for that.

**Comment by Airblader** [comment]
> perhaps it's a good idea to have the unit tests check the Xlib and this library produce the same results?

Yes, it would. I was thinking of doing this in `xrmq`, but doing it in the tests for `xcb-util-xrm` would make much more sense (classic d'oh moment). I've opened #13 for it.

**Comment by Airblader** [comment]
I've implemented this in xrmq now (albeit rather quick'n'dirty). It's quite simple, really. I'll probably implement that here before the first release.

**Comment by Airblader** [comment]
@psychon I've added the automatic comparison against Xlib now. Unfortunately there is one mismatch where Xlib is lenient despite it violating the specification. Since this would mean extra effort here and since I think it's not a common case, I'll accept the different to Xlib here.

IMHO, the only thing missing right now is the correct greediness of `*`. I don't think we need it for a first release – especially cairo, util-cursor etc. who so far only worked without loose bindings anyway won't have a problem with it. Frankly, I also refuse to believe that people actually use loose bindings *except* for something like `*color0` or `someapp*color0`. :)

**Comment by Airblader** [comment]
I'd actually like to make some minor changes to the API before this is used anywhere.

**Comment by Airblader** [comment]
(I'm just going to close this issue now since I will be tracking "must-haves" for a v1.0 release via label)

**Comment by psychon** [comment]
Thanks again for working on this. Awesome itself only queries `*color0` etc currently (and doesn't even use a class for its query :-( ), but provides an API to Lua for arbitrary queries (which I haven't seen used by anything else yet). So this library already does everything that awesome needs. :-)

**Comment by Airblader** [comment]
> So this library already does everything that awesome needs. :-)

That's good to know. :) Let's just wait a little bit longer anyway, I don't want to fully commit to the stability of the API quite yet. In fact, I might just end up sending the PR for awesome, depending on how easy it is (I reference awesome a lot when working on i3, but haven't hacket on it yet).

**Comment by Airblader** [comment]
On an interesting side note, somehow I only now realized that this has actually very little to do with X (or xcb). Really the only part directly related to X is getting the `RESOURCE_MANAGER` string. The rest is really just parsing and algorithm. So really, except for getting the resource string from the root window, this could be completely agnostic to whether it uses Xlib, xcb or whatever else.

But then again, there only are Xlib and xcb, for Xlib it already exists and Xlib still has the problem that it'll pull in *all* of Xlib.

**Comment by psychon** [comment]
> In fact, I might just end up sending the PR for awesome, depending on how easy it is

Look at xrdb.c and xrdb.h (and perhaps globalconf.h to change globalconf.xrmdb). The C code should be trivial to change. The CMake-integration might be harder, but might as easy as adding `xcb-xrm` to the list of pkg-config modules in `awesomeConfig.cmake` (next to xcb-xkb). And by my experience, having Travis install the dependencies always causes the most problems. ;-)

> But then again, there only are Xlib and xcb, for Xlib it already exists and Xlib still has the problem that it'll pull in all of Xlib.

Awesome uses cairo and that already pulls in Xlib everywhere, but I agree, that using Xlib "just for this" is weird. :-)
